import { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Linking,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Consent version - increment this when policies change to re-prompt users
const CONSENT_VERSION = '1.0';
const CONSENT_STORAGE_KEY = 'k12buddy_ai_consent';

interface ConsentRecord {
  version: string;
  accepted_at: string;
  allow_child_ai: boolean;
}

export async function getConsentStatus(): Promise<ConsentRecord | null> {
  try {
    const stored = await AsyncStorage.getItem(CONSENT_STORAGE_KEY);
    if (!stored) return null;

    const consent: ConsentRecord = JSON.parse(stored);

    // Check if consent version matches current version
    if (consent.version !== CONSENT_VERSION) {
      return null; // Re-prompt for new version
    }

    return consent;
  } catch {
    return null;
  }
}

export async function hasValidConsent(): Promise<boolean> {
  const consent = await getConsentStatus();
  return consent !== null;
}

export default function ConsentScreen() {
  const [agreed, setAgreed] = useState(false);
  const [allowChildAI, setAllowChildAI] = useState(true);
  const [saving, setSaving] = useState(false);

  async function handleContinue() {
    if (!agreed) {
      Alert.alert(
        'Acknowledgment Required',
        'Please check the box to confirm you understand and agree before continuing.'
      );
      return;
    }

    setSaving(true);
    try {
      const consentRecord: ConsentRecord = {
        version: CONSENT_VERSION,
        accepted_at: new Date().toISOString(),
        allow_child_ai: allowChildAI,
      };

      await AsyncStorage.setItem(CONSENT_STORAGE_KEY, JSON.stringify(consentRecord));

      // Navigate to auth or main app
      router.replace('/auth');
    } catch (error) {
      Alert.alert('Error', 'Failed to save your preferences. Please try again.');
    } finally {
      setSaving(false);
    }
  }

  function openPrivacyPolicy() {
    Linking.openURL('https://guampaul.github.io/k12buddy-ai/privacy-policy.html');
  }

  function openTermsOfService() {
    Linking.openURL('https://guampaul.github.io/k12buddy-ai/terms-of-service.html');
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.logo}>🎓</Text>
          <Text style={styles.title}>AI Learning Acknowledgment</Text>
        </View>

        {/* Main Content Card */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Before you begin</Text>

          <Text style={styles.paragraph}>
            K-12Buddy AI provides educational assistance to support learning and practice.
          </Text>

          <View style={styles.bulletList}>
            <View style={styles.bulletItem}>
              <Text style={styles.bulletIcon}>📚</Text>
              <Text style={styles.bulletText}>
                <Text style={styles.bold}>Not a replacement</Text> — This app does not replace teachers, school instruction, or professional educational services.
              </Text>
            </View>

            <View style={styles.bulletItem}>
              <Text style={styles.bulletIcon}>🤖</Text>
              <Text style={styles.bulletText}>
                <Text style={styles.bold}>AI-generated content</Text> — Responses are generated by AI and may occasionally be inaccurate or incomplete.
              </Text>
            </View>

            <View style={styles.bulletItem}>
              <Text style={styles.bulletIcon}>👨‍👩‍👧</Text>
              <Text style={styles.bulletText}>
                <Text style={styles.bold}>Parental oversight</Text> — Parents or guardians are encouraged to review learning activities with their children.
              </Text>
            </View>

            <View style={styles.bulletItem}>
              <Text style={styles.bulletIcon}>🔒</Text>
              <Text style={styles.bulletText}>
                <Text style={styles.bold}>Data protection</Text> — Your data is handled according to our Privacy Policy, with special protections for children under 13.
              </Text>
            </View>
          </View>
        </View>

        {/* Agreement Checkboxes */}
        <View style={styles.agreementSection}>
          {/* Required checkbox */}
          <TouchableOpacity
            style={styles.checkboxRow}
            onPress={() => setAgreed(!agreed)}
            activeOpacity={0.7}
          >
            <View style={[styles.checkbox, agreed && styles.checkboxChecked]}>
              {agreed && <Text style={styles.checkmark}>✓</Text>}
            </View>
            <Text style={styles.checkboxLabel}>
              I understand and agree to continue
            </Text>
          </TouchableOpacity>

          {/* Optional parent toggle */}
          <TouchableOpacity
            style={styles.checkboxRow}
            onPress={() => setAllowChildAI(!allowChildAI)}
            activeOpacity={0.7}
          >
            <View style={[styles.checkbox, allowChildAI && styles.checkboxChecked]}>
              {allowChildAI && <Text style={styles.checkmark}>✓</Text>}
            </View>
            <Text style={styles.checkboxLabel}>
              Allow my child to use AI learning features
            </Text>
          </TouchableOpacity>
        </View>

        {/* Legal Links */}
        <View style={styles.linksSection}>
          <TouchableOpacity onPress={openPrivacyPolicy}>
            <Text style={styles.link}>Privacy Policy</Text>
          </TouchableOpacity>
          <Text style={styles.linkSeparator}>•</Text>
          <TouchableOpacity onPress={openTermsOfService}>
            <Text style={styles.link}>Terms of Service</Text>
          </TouchableOpacity>
        </View>

        {/* Continue Button */}
        <TouchableOpacity
          style={[
            styles.continueButton,
            !agreed && styles.continueButtonDisabled,
          ]}
          onPress={handleContinue}
          disabled={!agreed || saving}
        >
          <Text style={styles.continueButtonText}>
            {saving ? 'Saving...' : 'Continue'}
          </Text>
        </TouchableOpacity>

        {/* Footer note */}
        <Text style={styles.footerNote}>
          You will only see this once. We&apos;ll notify you if our policies change.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 48,
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  logo: {
    fontSize: 56,
    marginBottom: 12,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 24,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 16,
  },
  paragraph: {
    fontSize: 15,
    color: '#4B5563',
    lineHeight: 22,
    marginBottom: 20,
  },
  bulletList: {
    gap: 16,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  bulletIcon: {
    fontSize: 20,
    marginRight: 12,
    marginTop: 2,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  bold: {
    fontWeight: '600',
    color: '#1F2937',
  },
  agreementSection: {
    marginBottom: 24,
    gap: 16,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: '#4F46E5',
    borderColor: '#4F46E5',
  },
  checkmark: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    flex: 1,
    fontSize: 15,
    color: '#374151',
    lineHeight: 20,
  },
  linksSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  link: {
    fontSize: 14,
    color: '#4F46E5',
    fontWeight: '500',
  },
  linkSeparator: {
    marginHorizontal: 12,
    color: '#9CA3AF',
  },
  continueButton: {
    backgroundColor: '#4F46E5',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 16,
  },
  continueButtonDisabled: {
    backgroundColor: '#C7D2FE',
  },
  continueButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#fff',
  },
  footerNote: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 18,
  },
});
